// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Song struct {
	ID   int64
	Name string
}

type SongHash struct {
	ID       int64
	SongID   int64
	SongHash int64
}
