// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Song struct {
	ID   int64
	Name string
}

type SongHash struct {
	ID       int64
	SongID   sql.NullInt64
	SongHash sql.NullInt64
}
